import test from 'node:test';
import assert from 'node:assert/strict';
import {probeRksiOnce} from '../scripts/probe-rksi-metar-once.mjs';
const key='fixture-not-a-real-credential';
const envelope=(station='RKSI')=>({response:{header:{resultCode:'00'},body:{pageNo:1,numOfRows:100,totalCount:1,items:{item:[{msgText:`METAR ${station} 061300Z 18008KT CAVOK 19/12 Q1016=`, 'om:phenomenonTime':'2026-10-06T13:00:00Z','iwxxm:airTemperature':19,untrusted:key}]}}}});
test('fixed official endpoint, one request, explicit limits and safe contract metadata',async()=>{
 let calls=0;const p=await probeRksiOnce({serviceKey:key,fetchImpl:async(url,options)=>{calls++;assert.equal(url.origin,'https://apis.data.go.kr');assert.equal(url.pathname,'/1360000/AmmIwxxmService/getMetar');assert.equal(url.searchParams.get('ServiceKey'),key);assert.equal(url.searchParams.get('icao'),'RKSI');assert.equal(url.searchParams.get('numOfRows'),'100');assert.equal(options.redirect,'error');assert.ok(options.signal);return Response.json(envelope());}});
 assert.equal(calls,1);assert.equal(p.status,'VERIFIED_CONTRACT');assert.equal(p.timeoutMs,10000);assert.equal(p.maxBodyBytes,1048576);assert.equal(p.matchedStationCount,1);assert.deepEqual(p.observationTimes,['2026-10-06T13:00:00Z']);assert.equal(JSON.stringify(p).includes(key),false);assert.equal(JSON.stringify(p).includes('METAR RKSI'),false);
});
test('missing credential sends no request',async()=>{let calls=0;const p=await probeRksiOnce({fetchImpl:async()=>{calls++;}});assert.equal(p.status,'CREDENTIAL_NOT_CONFIGURED');assert.equal(calls,0);});
test('network exception containing credential or URL is never logged and has no retry',async()=>{let calls=0;const p=await probeRksiOnce({serviceKey:key,fetchImpl:async()=>{calls++;throw Error(`https://example.invalid/?ServiceKey=${key}`);}});assert.equal(calls,1);assert.equal(p.status,'REQUEST_FAILED');assert.equal(JSON.stringify(p).includes(key),false);assert.equal(JSON.stringify(p).includes('https://'),false);});
test('timeout has no retry',async()=>{let calls=0;const p=await probeRksiOnce({serviceKey:key,fetchImpl:async()=>{calls++;throw new DOMException('discarded','TimeoutError');}});assert.equal(calls,1);assert.equal(p.status,'REQUEST_TIMEOUT');});
test('streaming byte limit rejects and cancels an oversized response',async()=>{let cancelled=false;const stream=new ReadableStream({start(controller){controller.enqueue(new Uint8Array(1048577));},cancel(){cancelled=true;}});const p=await probeRksiOnce({serviceKey:key,fetchImpl:async()=>new Response(stream)});assert.equal(p.status,'BODY_LIMIT_EXCEEDED');assert.equal(cancelled,true);});
test('XML authentication error keeps only safe code',async()=>{const p=await probeRksiOnce({serviceKey:key,fetchImpl:async()=>new Response(`<OpenAPI_ServiceResponse><cmmMsgHeader><returnReasonCode>30</returnReasonCode><errMsg>${key}</errMsg></cmmMsgHeader></OpenAPI_ServiceResponse>`)});assert.equal(p.status,'AUTH_BLOCKED');assert.equal(p.providerCode,'30');assert.equal(JSON.stringify(p).includes(key),false);});
test('another station cannot pass RKSI contract',async()=>{const p=await probeRksiOnce({serviceKey:key,fetchImpl:async()=>Response.json(envelope('RKSS'))});assert.equal(p.status,'SHAPE_UNVERIFIED');assert.equal(p.matchedStationCount,0);});
test('calendar rollover and incomplete pagination fail closed',async()=>{const fixture=envelope();fixture.response.body.items.item[0]['om:phenomenonTime']='2026-02-30T13:00:00Z';let p=await probeRksiOnce({serviceKey:key,fetchImpl:async()=>Response.json(fixture)});assert.equal(p.status,'SHAPE_UNVERIFIED');fixture.response.body.items.item[0]['om:phenomenonTime']='2026-10-06T13:00:00Z';fixture.response.body.totalCount=101;p=await probeRksiOnce({serviceKey:key,fetchImpl:async()=>Response.json(fixture)});assert.equal(p.status,'SHAPE_UNVERIFIED');});
