import type {Lang} from './retailpulse-data';
export const departureChoiceAssets={T1:'/visuals/departure-choices/v1/terminal-t1-256.webp',T2:'/visuals/departure-choices/v1/terminal-t2-256.webp',T1_CONCOURSE:'/visuals/departure-choices/v1/concourse-256.webp',UNKNOWN:'/visuals/departure-choices/v1/help-sign-256.webp',checked:'/visuals/clarity/v1/checked-bag-256.webp',carry:'/visuals/clarity/v1/cabin-bag-256.webp',refund:'/visuals/departure-choices/v1/refund-receipt-256.webp',pickup:'/visuals/clarity/v1/shopping-bag-256.webp',before:'/visuals/departure-choices/v1/security-check-256.webp',after:'/visuals/departure-choices/v1/immigration-pass-256.webp'} as const;
const text={
 ko:{unknown:'모름',bagYes:'필요한 신고·검사 후 항공사 안내에 따라 짐을 보내세요.',bagNo:'기내수하물 규정과 반입 제한 물품을 확인하세요.',taxYes:'환급 서류와 물품을 준비하고 신청 자격을 확인하세요.',taxNo:'세금환급 절차를 제외합니다.',pickupYes:'주문서의 인도장과 필요한 서류를 확인하세요.',pickupNo:'면세품 수령 절차를 제외합니다.',unsure:'확인 전에는 해당 절차가 필요 없다고 판단하지 마세요.',goodsBag:'검사 대상 환급 물품이 든 가방',packing:'위탁짐 유무와 별개의 선택입니다. 실제 물품이 든 가방을 확인하세요.'},
 en:{unknown:'Unsure',bagYes:'Hand over your bag after required declarations and inspections.',bagNo:'Check cabin-baggage rules and restricted items.',taxYes:'Prepare refund documents and goods; confirm eligibility.',taxNo:'Tax-refund steps are excluded.',pickupYes:'Check the pickup counter and documents on your order.',pickupNo:'Duty-free pickup steps are excluded.',unsure:'Confirm this choice before assuming the procedure is unnecessary.',goodsBag:'Bag containing refund goods selected for inspection',packing:'Separate from having a checked bag. Confirm where the goods are packed.'},
 zh:{unknown:'不确定',bagYes:'完成必要申报及检查后，按航空公司指示托运。',bagNo:'确认随身行李规定及限制携带物品。',taxYes:'准备退税单及商品，确认申请资格。',taxNo:'不显示退税步骤。',pickupYes:'确认订单所列提货地点及所需文件。',pickupNo:'不显示免税品领取步骤。',unsure:'确认之前，不要认为该手续无需办理。',goodsBag:'待检查的退税商品放在哪个行李中',packing:'与是否有托运行李不同，请确认商品的实际存放位置。'},
 ja:{unknown:'不明',bagYes:'必要な申告・検査後、航空会社の案内に従って荷物を預けます。',bagNo:'機内持ち込みの規定と制限品を確認します。',taxYes:'還付書類と品物を用意し、申請条件を確認します。',taxNo:'税金還付の手順を除きます。',pickupYes:'注文書の受取場所と必要書類を確認します。',pickupNo:'免税品受け取りの手順を除きます。',unsure:'確認前に、その手続きが不要だと判断しないでください。',goodsBag:'検査対象の還付品を入れた荷物',packing:'預け入れ荷物の有無とは別です。品物を入れた荷物を確認してください。'},
};
export const departureChoiceCopy=(lang:Lang)=>text[lang];
