import type { Lang } from './retailpulse-data';
const row = (ko: string, en: string, zh: string, ja: string) => ({ ko, en, zh, ja });
export const recordsCopy = {
  title: row('월별로 쌓인 기록', 'Records by month', '逐月积累的记录', '月ごとの記録'),
  intro: row('지역과 월을 골라 일평균 체류 인구를 전월과 비교하세요.', 'Choose an area and month to compare daily mean population with the previous month.', '选择地区和月份，将日均在场人口与上月比较。', 'エリアと月を選び、日平均滞在人口を前月と比較できます。'),
  area: row('지역', 'Area', '地区', 'エリア'), month: row('조회 월', 'Month', '查询月份', '対象月'),
  metric: row('일평균 체류 인구', 'Daily mean population present', '日均在场人口', '日平均滞在人口'),
  unit: row('명', 'people', '人', '人'), selected: row('선택한 달', 'Selected month', '所选月份', '選択した月'),
  previous: row('전월', 'Previous month', '上月', '前月'), compare: row('전월 일평균 대비', 'Vs. previous daily mean', '与上月日均相比', '前月の日平均比'),
  included: row('포함', 'included', '计入', '算入'), days: row('일', 'days', '天', '日'),
  cutoff: row('집계 마감', 'Cutoff', '统计截止', '集計締切'), none: row('집계 가능한 날 없음', 'No complete days', '无完整日期', '集計可能な日なし'),
  pending: row('집계 중 · 오늘 제외', 'In progress · today excluded', '统计中 · 不含今天', '集計中・本日を除く'),
  daily: row('일별 평균 범위', 'Daily mean ranges', '每日平均区间', '日別平均の範囲'),
  note: row('24개 시간대가 모두 있는 날만 포함합니다. 빈 날은 0명이 아닙니다.', 'Only days with all 24 hourly samples count. Missing days do not mean zero people.', '仅计入24个小时样本齐全的日期。缺失不等于0人。', '24時間分が揃った日のみ算入。欠測は0人ではありません。'),
  peopleNote: row('하루 방문객 수와 구분되는 시간별 체류 인구의 평균입니다.', 'An average of hourly population present, not a daily visitor count.', '这是每小时在场人口的平均值，并非每日访客总数。', '時間ごとの滞在人口の平均です。1日の来訪者数ではありません。'),
  comparing: row('포함 일수가 다른 부분 기록끼리의 비교입니다.', 'Partial records with different coverage may be compared.', '比较的部分记录可能涵盖不同数量的日期。', '収録日数の異なる部分記録を比較しています。'),
  unavailableCompare: row('양쪽 달의 완결일 자료가 있어야 비교할 수 있습니다.', 'Complete-day records in both months are needed for comparison.', '两个月均需有完整日期的记录才能比较。', '比較には両月の完全な日別記録が必要です。'),
  details: row('집계 기준·보관 범위', 'Calculation and stored range', '计算方法与保存范围', '集計方法・保存範囲'),
  method: row('한국시간 00~23시, 각 1시간 안의 마지막 관측을 하나씩 고릅니다. 같은 지역 코드·출처·정의의 유효 관측 24개가 모두 있어야 하루 평균에 포함합니다. 최소값과 최대값을 각각 24로 나눈 뒤, 완결일들을 같은 비중으로 평균합니다. 결측·미완결일·진행 중인 오늘은 분모에서 제외합니다.', 'For each KST hour 00–23, use the last observation within that hour. A day needs all 24 valid samples with the same area code, source and definition. Average lower and upper bounds separately, then weight complete days equally. Missing, incomplete and ongoing days are excluded from the denominator.', '韩国时间00至23时，每小时取该小时内最后一次观测。每天必须具备相同地区代码、来源和定义的24个有效样本。分别计算上下限均值，再对完整日期等权平均。缺失、不完整及今天均不计入分母。', '韓国時間00〜23時の各時間内の最終観測を1件ずつ使用。同一エリアコード・出典・定義の有効な24件が揃う日が対象です。下限・上限を別々に平均し、完全な日を等しく重み付けします。欠測・不完全日・進行中の本日は分母から除きます。'),
  comparisonMethod: row('선택한 달은 마감일까지, 전월은 한 달 전체의 완결일 평균입니다. 관측 범위를 유지해 증감도 범위로 계산하며, 인구를 합산하거나 중간값으로 단정하지 않습니다.', 'The selected month runs through its cutoff; the previous month uses its full calendar month. Both average complete days. Change retains the published ranges, without population totals or invented midpoints.', '所选月份截至统计日，上月按整个自然月，均仅平均完整日期。变化保留区间，不合计人口或使用推测中点。', '選択月は締切日まで、前月は暦月全体の完全な日を平均。増減も範囲で示し、人口の合計や推定中央値は使いません。'),
  stored: row('보관 관측 범위', 'Stored observation range', '保存的观测范围', '保存された観測期間'),
  storedNote: row('보관 범위 안에도 빠진 시간·날짜가 있을 수 있습니다.', 'Hours and dates may be missing within this range.', '该范围内也可能缺少小时或日期。', 'この期間内にも欠測時間・欠測日があります。'),
  sourceLimit: row('원자료는 단기체류 외국인(90일 이하)을 인구 추정에서 제외합니다.', 'The source excludes short-stay foreigners (90 days or less) from its population estimate.', '原始人口估算不含短期停留外国人（90天及以下）。', '原資料の人口推計は短期滞在外国人（90日以下）を除きます。'),
  source: row('서울시 공식 도시데이터', 'Official Seoul city data', '首尔市官方城市数据', 'ソウル市公式都市データ'),
  calculated: row('공식 관측으로 KORETAIL 계산', 'Calculated by KORETAIL from official observations', 'KORETAIL根据官方观测计算', '公式観測からKORETAILが算出'),
  dayList: row('날짜별 포함·제외 내역', 'Included and excluded dates', '计入与排除日期', '算入・除外日一覧'),
  date: row('날짜', 'Date', '日期', '日付'), coverage: row('시간 자료', 'Hourly samples', '小时样本', '時間別資料'),
  status: row('집계 상태', 'Status', '状态', '集計状況'), complete: row('포함', 'Included', '计入', '算入'),
  partial: row('시간 부족 · 제외', 'Incomplete · excluded', '小时不足 · 排除', '時間不足・除外'),
  missing: row('자료 없음 · 제외', 'Missing · excluded', '无资料 · 排除', '資料なし・除外'),
  progress: row('진행 중 · 제외', 'In progress · excluded', '进行中 · 排除', '進行中・除外'),
  loading: row('월별 기록을 불러오는 중입니다.', 'Loading monthly records.', '正在加载月度记录。', '月別記録を読み込み中です。'),
  error: row('월별 기록을 불러오지 못했습니다.', 'Monthly records could not be loaded.', '无法加载月度记录。', '月別記録を読み込めませんでした。'),
  retry: row('다시 불러오기', 'Retry', '重试', '再読み込み'),
  reference: row('공식 장기 통계·예측 검증 안내', 'Official long-term statistics and forecast validation', '官方长期统计与预测验证', '公式長期統計・予測検証の案内'),
} as const;
export function recordText(key: keyof typeof recordsCopy, lang: Lang): string { return recordsCopy[key][lang] ?? recordsCopy[key].en; }
