import type {Lang} from './retailpulse-data';

export const passengerGuideCopy={
 ko:{overview:'수속부터 탑승까지 · 5단계',titles:['터미널 확인','체크인·수하물','보안검색','출국심사','탑승게이트'],sentences:['항공권에서 출발 터미널과 탑승 위치를 확인하세요.','항공사에서 체크인하고 필요한 확인 후 짐을 인계하세요.','반입 제한 물품을 확인하고 보안검색을 받으세요.','여권과 탑승권을 준비해 출국심사를 받으세요.','최신 게이트와 탑승 마감시간을 확인하고 이동하세요.'],details:'자세히 확인',plan:'선택한 항목의 세부 순서',optional:'세금환급 · 대상자만 선택',eligibility:'국내 거주 일반 내국인은 통상 환급 대상이 아닙니다. 해외 거주 예외 등은 공식 대상 안내를 확인하세요.',learning:'그림과 펼친 안내는 절차를 이해하기 위한 자료입니다. 화면 조작은 실제 수속·검사·환급 완료를 확인하지 않습니다.'},
 en:{overview:'Check-in to boarding · 5 steps',titles:['Confirm terminal','Check-in & baggage','Security screening','Departure immigration','Boarding gate'],sentences:['Confirm your departure terminal and boarding location on your ticket.','Check in with your airline and hand over bags after required checks.','Check restricted items and pass security screening.','Have your passport and boarding pass ready for immigration.','Check the latest gate and boarding deadline before proceeding.'],details:'View details',plan:'Detailed order for your choices',optional:'Tax refund · eligible travelers only',eligibility:'Ordinary Korean residents generally do not qualify. Check official eligibility for overseas-resident exceptions and other conditions.',learning:'Illustrations and expanded guidance explain the procedure. Using this screen does not verify actual check-in, inspection or refund completion.'},
 zh:{overview:'值机至登机 · 5步',titles:['确认航站楼','值机及行李','安检','出境审查','登机口'],sentences:['在机票上确认出发航站楼和登机位置。','向航空公司办理值机，完成必要确认后托运行李。','确认限制携带物品并接受安检。','准备护照和登机牌，接受出境审查。','确认最新登机口和截止时间后前往。'],details:'查看详情',plan:'所选项目的详细顺序',optional:'退税 · 仅符合条件者选择',eligibility:'通常居住在韩国的普通韩国公民不符合退税条件。海外居民例外及其他条件请查看官方资格说明。',learning:'图片和展开的说明用于了解流程。操作此页面不表示已完成值机、检查或退税。'},
 ja:{overview:'チェックインから搭乗まで · 5段階',titles:['ターミナル確認','チェックイン・荷物','保安検査','出国審査','搭乗ゲート'],sentences:['航空券で出発ターミナルと搭乗場所を確認してください。','航空会社でチェックインし、必要な確認後に荷物を預けてください。','持ち込み制限品を確認し、保安検査を受けてください。','パスポートと搭乗券を用意して出国審査を受けてください。','最新ゲートと搭乗締切を確認して移動してください。'],details:'詳しく確認',plan:'選択した項目の詳しい順序',optional:'税金還付 · 対象者のみ選択',eligibility:'通常、韓国に居住する一般の韓国人は対象外です。海外居住者の例外などは公式の対象案内を確認してください。',learning:'図と展開した案内は手順を理解する資料です。画面操作で実際の手続き・検査・還付の完了は確認できません。'},
};
export const getPassengerGuideCopy=(lang:Lang)=>passengerGuideCopy[lang]??passengerGuideCopy.en;
