import {test,expect} from '@playwright/test';import {routeSummary,SUMMARY_FIXTURE} from './summary-fixture';import {departurePreparationCopy} from '../app/airport-departure-preparation-copy';import {taxRefundCopy} from '../app/airport-tax-refund-copy';import {tofuCharacters} from './font-glyphs';
for(const lang of ['ko','en','zh','ja'] as const)for(const width of [320,390,430,1280])test(`departure preparation ${lang} ${width}: selected tasks and unknown fallback`,async({page})=>{
 await page.setViewportSize({width,height:900});await page.emulateMedia({reducedMotion:'reduce'});const c=departurePreparationCopy[lang],tax=taxRefundCopy[lang],errors:string[]=[];let rasterReads=0;page.on('pageerror',error=>errors.push(error.message));page.on('console',message=>{if(message.type()==='error')errors.push(message.text());});page.on('request',request=>{if(request.url().includes('/tax-refund/'))rasterReads++;});
 await page.route('**/api/live/summary*',routeSummary(SUMMARY_FIXTURE));await page.route('**/api/live/flights*',r=>r.fulfill({json:{mode:'live-flights',flights:[],truncated:false,retrievedAt:'2026-08-31T03:00:00Z'}}));
 await page.goto(`/${lang}/airport`);await expect(page.locator('.app')).toHaveAttribute('data-hydrated','true');const prep=page.getByTestId('departure-preparation');await expect(prep.locator('select')).toHaveCount(0);expect(rasterReads).toBe(0);
 await page.locator('.airport-purpose-links').getByRole('link',{name:c.title,exact:true}).focus();await page.keyboard.press('Enter');await expect(prep.getByTestId('prep-unknown-route')).toBeVisible();await expect(prep.getByTestId('prep-plan')).toHaveCount(0);
 await prep.getByTestId('prep-route').selectOption('T2');for(const key of ['checkedBaggage','taxRefund','dutyFreePickup'])await prep.getByTestId(`prep-${key}`).selectOption('NO');await expect(prep.locator('[data-step=PICKUP]')).toHaveCount(0);await expect(prep.locator('[data-step=REFUND]')).toHaveCount(0);await expect(prep.locator('[data-step=BAG_DROP]')).toHaveCount(0);await expect(prep.getByTestId('tax-refund-guide')).toHaveCount(0);
 await prep.getByTestId('prep-plan').locator(':scope > summary').focus();await page.keyboard.press('Enter');
 for(const key of ['checkedBaggage','taxRefund','dutyFreePickup'])await prep.getByTestId(`prep-${key}`).selectOption('YES');await expect(prep.locator('[data-step=CHECKED_CUSTOMS]')).toHaveAttribute('data-conditional','true');await expect(prep.locator('[data-step=CHECKED_CUSTOMS]')).toHaveText(new RegExp(c.checkedCustoms.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));await expect(prep.getByTestId('prep-carry-customs')).toHaveText(c.carryNote);
 const order=await prep.getByTestId('prep-plan').locator('[data-step]').evaluateAll(els=>els.map(el=>el.getAttribute('data-step')));expect(order.indexOf('CHECKED_CUSTOMS')).toBeLessThan(order.indexOf('BAG_DROP'));expect(order.indexOf('BAG_DROP')).toBeLessThan(order.indexOf('SECURITY'));expect(order.indexOf('IMMIGRATION')).toBeLessThan(order.indexOf('PICKUP'));
 await expect(prep.locator('[data-step=PICKUP]')).toContainText(c.pickupStep);const guide=prep.getByTestId('tax-refund-guide');await guide.locator(':scope >summary').click();await expect(guide.locator('img[src*="/passenger-guide/"]')).toHaveCount(2);await expect(guide.locator('img[src*="/v2/"]')).toHaveCount(2);await guide.getByRole('button',{name:tax.after,exact:true}).click();await expect(guide.getByTestId('tax-t2-conflict')).toHaveText(tax.conflict);
 await guide.getByText(tax.sourceDetails,{exact:true}).click();await guide.getByText(tax.eligibility,{exact:true}).click();await guide.getByText(tax.sources,{exact:true}).click();expect(await tofuCharacters(prep)).toEqual([]);
 await prep.getByTestId('prep-route').selectOption('T1_CONCOURSE');await expect(prep.getByTestId('prep-concourse-note')).toHaveText(c.concourseNote);await prep.getByTestId('prep-checkedBaggage').selectOption('NO');await expect(prep.locator('[data-step=CHECKED_CUSTOMS]')).toHaveCount(0);await expect(prep.getByTestId('prep-carry-customs')).toBeVisible();
 await prep.getByTestId('prep-route').selectOption('UNKNOWN');await expect(prep.getByTestId('prep-plan')).toHaveCount(0);await expect(prep.getByTestId('tax-refund-guide')).toHaveCount(0);await prep.getByTestId('prep-route').selectOption('T1');await prep.getByTestId('prep-taxRefund').selectOption('UNKNOWN');await expect(prep.getByTestId('prep-unknown-choices')).toBeVisible();await expect(prep.locator('[data-step=REFUND]')).toHaveCount(0);
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);expect(errors).toEqual([]);await expect(page.getByTestId('airport-departure-overview')).toHaveCount(1);
});
