export const zoneShareCopy = {
  ko: {
    basis: '구역 비율: 같은 건물·날짜·시간의 전체 항공편 기준, 위치 미확인 포함.',
    rounding: '표시 비율은 반올림으로 합계가 100%와 다를 수 있습니다.',
    zero: '비율 계산 안 함',
    gatesPending: '게이트 위치 확인 전',
    country: '국가 비율: 해당 구역의 전체 항공편 기준, 목적지 미확인 포함.',
    unavailable: '이 날짜의 운항 자료가 아직 확인되지 않았습니다. 확인된 0편이 아닙니다.',
    concept: '공식 지도 위치를 바탕으로 코리테일이 구분한 구역입니다. 중앙은 코리테일 분류이며, 모형은 실제 좌표가 아닙니다.',
  },
  en: {
    basis: 'Zone shares: all flights in the same building, date and time window, including unverified locations.',
    rounding: 'Rounded percentages may not add up to 100%.',
    zero: 'Share not calculated',
    gatesPending: 'Gate locations not yet confirmed',
    country: 'Country shares: all flights in that zone, including unknown destinations.',
    unavailable: 'Flight records for this date have not been confirmed. This is not a confirmed zero.',
    concept: 'KORETAIL zones based on official map positions. The central zone is a KORETAIL classification; this model does not show actual coordinates.',
  },
  zh: {
    basis: '区域比例：同一航站楼、日期和时段的全部航班，包括位置未确认的航班。',
    rounding: '显示比例经过四舍五入，合计可能不等于100%。',
    zero: '未计算比例',
    gatesPending: '登机口位置尚未确认',
    country: '国家比例：该区域的全部航班，包括目的地未知的航班。',
    unavailable: '此日期的航班资料尚未确认，并非已确认的零航班。',
    concept: 'KORETAIL根据官方地图位置划分的区域。中央区域由KORETAIL分类，模型并非实际坐标。',
  },
  ja: {
    basis: '区域の割合：同じ建物・日付・時間帯の全便が基準です。位置未確認の便も含みます。',
    rounding: '表示割合は丸めにより合計が100%にならない場合があります。',
    zero: '割合は未計算',
    gatesPending: '搭乗口の位置は未確認',
    country: '国の割合：その区域の全便が基準です。目的地不明の便も含みます。',
    unavailable: 'この日付の運航資料はまだ確認できません。確認済みの0便ではありません。',
    concept: '公式地図の位置を基にKORETAILが分けた区域です。中央はKORETAILの分類で、模型は実際の座標ではありません。',
  },
};
