export type PersonalLang = 'ko' | 'en' | 'zh' | 'ja';
const row = (ko: string, en: string, zh: string, ja: string) => ({ko,en,zh,ja});
export const personalCopy = {
  multiple: row('여러 개 선택할 수 있어요. 최소 하나는 선택해 주세요.','Choose one or more options.','可选择多项，请至少保留一项。','複数選択できます。1つ以上選んでください。'),
  switchBriefing: row('선택한 지역·날짜 보기','View your selected places and days','查看所选地区与日期','選択した場所・日付を見る'),
  yesterday: row('어제 브리핑','Yesterday’s briefing','昨日简报','昨日のブリーフィング'),
  pastNote: row('어제 날짜의 저장된 자료입니다. 예상값은 실제 결과와 구분해 표시합니다.','Stored information for yesterday. Forecasts remain distinct from actual outcomes.','昨日已保存的资料。预测与实际结果分别标示。','昨日の保存済み資料です。予測と実績を区別して表示します。'),
  pastSeoulNote: row('상권의 어제 인구·혼잡·날씨는 현재 제공하지 않습니다. 확인되는 일정과 과거 공개자료만 표시합니다.','Yesterday’s neighbourhood population, crowding and weather are not currently available. Only available schedules and published history are shown.','目前不提供商圈昨日人口、拥挤和天气。仅显示可用日程与已发布历史资料。','街の昨日の人口・混雑・天気は現在提供していません。確認できる予定と公表済みの過去資料のみ表示します。'),
  noLocalInterests: row('선택한 지역에 해당하는 관심정보가 없어요. 내 설정에서 필요한 정보를 추가해 주세요.','None of your selected interests apply to this place. Add interests in your settings.','所选关注信息不适用于该地区，请在设置中添加。','選択した関心情報はこの場所に対応していません。設定で追加してください。'),
  promise: row('오늘·내일 필요한 공항·관광·상권 정보를 한 번에 확인하세요.', 'Your airport, travel and neighbourhood briefing for today and tomorrow.', '一站查看今天和明天所需的机场、旅游与商圈信息。', '今日・明日に必要な空港・観光・街の情報をまとめて確認。'),
  role: row('어떤 목적으로 이용하시나요?', 'What brings you here?', '您主要用于什么目的？', 'どのような目的で利用しますか？'),
  location: row('어느 지역을 보고 싶으신가요?', 'Which places would you like to see?', '您想查看哪些地区？', 'どの場所を確認したいですか？'),
  interests: row('어떤 정보가 가장 중요하신가요?', 'What matters most to you?', '哪些信息最重要？', 'どの情報が重要ですか？'),
  preference: row('어느 날짜의 브리핑을 볼까요?', 'Which days would you like to see?', '您想查看哪些日期的简报？', 'どの日付のブリーフィングを見ますか？'),
  tourist: row('관광객', 'Traveller', '游客', '旅行者'),
  manager: row('매장 영업관리자', 'Store manager', '门店营业管理者', '店舗営業管理者'),
  guide: row('관광통역안내사', 'Tour guide', '旅游翻译导游', '観光通訳ガイド'),
  touristNote: row('혼잡·날씨·행사·공항 이동 중심', 'Crowds, weather, events and airport travel', '拥挤、天气、活动与机场出行', '混雑・天気・イベント・空港移動'),
  managerNote: row('이용객·항공편·혼잡·외국인 흐름·영업 준비 중심', 'Passengers, flights, crowds and store preparation', '旅客、航班、拥挤、外国人动向与营业准备', '利用者・便数・混雑・外国人動向・営業準備'),
  guideNote: row('관광객 흐름·행사·날씨·공항·관광안내 중심', 'Visitor context, events, weather and airport guidance', '游客动向、活动、天气、机场与旅游咨询', '観光客動向・イベント・天気・空港・観光案内'),
  airport: row('인천공항', 'Incheon Airport', '仁川机场', '仁川空港'),
  myeongdong: row('명동','Myeongdong','明洞','明洞'),
  hongdae: row('홍대','Hongdae','弘大','弘大'),
  seongsu: row('성수','Seongsu','圣水','聖水'),
  all: row('전체','All','全部','全体'),
  CONCOURSE: row('탑승동','Concourse','登机楼','コンコース'),
  passengers: row('예상 이용객·인구','Expected passengers / population','预计旅客与人口','予想利用者・人口'),
  crowding: row('혼잡·붐비는 시간','Crowding and busy hours','拥挤与高峰时段','混雑・混み合う時間'),
  flights: row('항공편 흐름','Flight activity','航班动向','フライト動向'),
  timeBasis: row('한국시간 기준','All times are Korea time','所有时间均为韩国时间','時刻はすべて韓国時間'),
  myBriefing: row('내 브리핑','My briefing','我的简报','マイブリーフ'),
  flightUnit: row('편',' flights','班','便'),
  peopleUnit: row('명',' people','人','人'),
  scheduledFlights: row('등록된 출발 일정','Registered departure schedules','已登记出发计划','登録済み出発予定'),
  scheduleBasis: row('선택 날짜·요일의 일부 면세점 연계 일정 · 전체 운항편 수나 운항 실적 아님','Partial duty-free-linked schedules for this date and weekday · not all flights or observed operations','所选日期及星期的部分免税店相关计划 · 非全部航班或实际运行','選択日・曜日の一部免税店関連予定・全便数や運航実績ではありません'),
  flightsMissing: row('선택한 날짜·터미널의 운항 기록과 등록 일정이 아직 없습니다.','No flight records or registered schedules for this date and terminal yet.','暂无所选日期与航站楼的航班记录或登记计划。','選択日・ターミナルの運航記録や登録予定はまだありません。'),
  airlinesMissing: row('선택한 날짜·터미널의 항공사별 자료가 아직 없습니다.','Airline breakdown is not available for this date and terminal yet.','暂无所选日期与航站楼的航空公司分类资料。','選択日・ターミナルの航空会社別資料はまだありません。'),
  airlines: row('주요 항공사·등록 국가','Leading airlines and registration countries','主要航空公司与注册国','主な航空会社・登録国'),
  airlineBasis: row('항공사 등록 국가 · 승객 국적이나 관광객 수 아님','Airline registration country · not passenger nationality or tourist counts','航空公司注册国 · 非旅客国籍或游客人数','航空会社の登録国・乗客の国籍や観光客数ではありません'),
  foreign: row('외국인 흐름 · 과거 공식 자료','Foreign presence · official history','外国人动向 · 官方历史资料','外国人動向・公式の過去資料'),
  weather: row('날씨','Weather','天气','天気'),
  events: row('행사','Events','活动','イベント'),
  guidance: row('관광안내 브리핑','Guide desk briefing','旅游咨询简报','観光案内ブリーフィング'),
  today: row('오늘 브리핑','Today’s briefing','今日简报','今日のブリーフィング'),
  tomorrow: row('내일 브리핑','Tomorrow’s briefing','明日简报','明日のブリーフィング'),
  managerToday: row('오늘 영업 브리핑','Today’s store briefing','今日营业简报','今日の営業ブリーフィング'),
  managerTomorrow: row('내일 영업 브리핑','Tomorrow’s store briefing','明日营业简报','明日の営業ブリーフィング'),
  guideToday: row('오늘 안내업무 브리핑','Today’s guide briefing','今日导游工作简报','今日のガイド業務ブリーフィング'),
  guideTomorrow: row('내일 안내업무 브리핑','Tomorrow’s guide briefing','明日导游工作简报','明日のガイド業務ブリーフィング'),
  touristPromise: row('오늘 여행에 필요한 정보만 바로 확인하세요.','See what you need for today’s trip.','直接查看今天旅行所需的信息。','今日の旅行に必要な情報をすぐ確認。'),
  managerPromise: row('내일 영업을 오늘 준비하세요.','Prepare today for tomorrow’s business.','今天准备好明天的营业。','明日の営業を今日準備しましょう。'),
  guidePromise: row('오늘 안내 업무에 필요한 관광·공항 정보를 한 번에 확인하세요.','Tourism and airport information for your guiding day.','一站查看今天导游工作所需的旅游与机场信息。','今日の案内業務に必要な観光・空港情報をまとめて確認。'),
  next: row('다음','Next','下一步','次へ'), back: row('이전','Back','上一步','戻る'),
  finish: row('내 브리핑 보기','Show my briefing','查看我的简报','自分のブリーフィングを見る'),
  settings: row('내 설정 보기','My settings','我的设置','自分の設定'),
  edit: row('설정 변경','Change settings','更改设置','設定を変更'),
  reset: row('처음부터 다시 설정','Start setup again','重新设置','最初から設定'),
  cancel: row('취소','Cancel','取消','キャンセル'),
  remembered: row('이 기기에서 설정을 기억합니다.','Your settings are remembered on this device.','在此设备上记住您的设置。','この端末で設定を記憶します。'),
  storageNote: row('브라우저나 앱의 데이터를 지우거나 앱을 삭제하면 설정이 없어질 수 있어요. 다른 브라우저나 기기에는 이어지지 않아요.','Clearing browser or app data, or removing the app, may erase settings. They do not transfer to other browsers or devices.','清除浏览器或应用数据、删除应用可能会清除设置。设置不会同步到其他浏览器或设备。','ブラウザやアプリのデータ消去・アプリ削除で設定が消える場合があります。他のブラウザや端末には引き継がれません。'),
  storageError: row('이 기기에 저장하지 못했어요. 지금은 사용할 수 있지만 다시 열면 설정이 사라질 수 있어요.','Settings could not be saved here. You can continue, but they may disappear when you reopen.','无法在此设备保存。仍可使用，但重新打开后设置可能丢失。','この端末に保存できませんでした。利用できますが、開き直すと設定が消える場合があります。'),
  details: row('자세히 보기','View details','查看详情','詳しく見る'),
  existing: row('기존 공항·상권·관광 데이터 자세히 보기','Explore the full airport, area and tourism data','查看完整机场、商圈与旅游资料','空港・街・観光の詳しいデータを見る'),
  empty: row('선택한 날짜에 확인된 자료가 아직 없어요. 자세한 화면에서 자료 제공 범위를 확인하세요.','No confirmed data for this date yet. Check the detailed view for coverage.','所选日期暂无已确认资料。请在详情页查看提供范围。','選択した日付の確認済み資料はまだありません。詳細画面で提供範囲をご確認ください。'),
  missing: row('아직 제공된 자료가 없어요','No published data yet','暂无已发布资料','まだ公表資料がありません'),
  forecast: row('공식 예상 · 관측값 아님','Official forecast · not observed','官方预测 · 非实测','公式予想・観測値ではありません'),
  partial: row('일부 시간대만 제공 · 하루 전체 예상 아님','Only some hours available · not a whole-day forecast','仅部分时段 · 非全天预测','一部時間帯のみ・一日全体の予想ではありません'),
  expectedDepartures: row('예상 출국객','Expected departing passengers','预计出境旅客','予想出国者数'),
  peak: row('제공된 예측 중 가장 붐빌 시간','Busiest hour in the published forecast','已发布预测中的最拥挤时段','公表予測内で最も混み合う時間'),
  current: row('현재 추정 인구 · 누적 방문객 아님','Estimated population now · not cumulative visitors','当前推定人口 · 非累计访客','現在の推定人口・累計来訪者ではありません'),
  stale: row('지난 관측 · 현재와 다를 수 있어요','Older observation · conditions may have changed','较早观测 · 当前状况可能不同','過去の観測・現在と異なる場合があります'),
  flightBasis: row('수집된 출발편 · 승객 국적을 뜻하지 않아요','Collected departing flights · not passenger nationality','已收集出发航班 · 不代表旅客国籍','収集済み出発便・乗客の国籍を示しません'),
  concourseNote: row('탑승동 별도 이용객 예상은 제공되지 않아요.','No separate passenger forecast for the concourse.','不提供登机楼单独的旅客预测。','コンコース単独の利用者予想はありません。'),
  rain: row('강수확률 최대','Maximum rain chance','最高降水概率','最大降水確率'),
  historic: row('과거 단기외국인 생활인구 · 관광객 수나 매출 아님','Historical short-stay foreign population · not tourist counts or sales','历史短期外国人生活人口 · 非游客数或销售额','過去の短期滞在外国人生活人口・観光客数や売上ではありません'),
  eventNote: row('공식 행사기간 기준 · 당일 운영은 확인 권장','Official event period · confirm daily opening','依据官方活动期间 · 建议确认当天开放情况','公式開催期間に基づく・当日の開催状況をご確認ください'),
  prepare: row('오늘 준비할 것','Prepare today','今天准备什么','今日準備すること'),
  visitPrep: row('예상 혼잡 시간과 방문 동선 확인 권장','Check busy hours and your route','建议确认拥挤时段与游览路线','混雑予想時間と訪問ルートを確認'),
  managerPrep: row('붐비는 시간대 인력 배치와 주요 상품 재고 확인 권장','Review staffing and key stock for busy hours','建议核对高峰时段人员安排与主要商品库存','混雑時間帯の人員配置と主要商品の在庫を確認'),
  guidePrep: row('집합 시간과 단체 이동 동선 확인 권장','Review meeting times and group routes','建议确认集合时间与团体路线','集合時間と団体の移動ルートを確認'),
  flightPrep: row('출발편·터미널·탑승구 변동 확인 권장','Check flight, terminal and gate updates','建议确认航班、航站楼与登机口变更','出発便・ターミナル・ゲート変更を確認'),
  weatherPrep: row('우천 시 이동 동선과 준비물 확인 권장','Review wet-weather routes and supplies','建议核对雨天路线与随身用品','雨天時の移動ルートと持ち物を確認'),
  eventPrep: row('행사 운영시간과 방문 가능 여부 확인 권장','Confirm event opening hours and access','建议确认活动时间与能否入场','イベントの開催時間と入場可否を確認'),
  helpful: row('이 브리핑이 도움이 됐나요?','Was this briefing helpful?','这份简报有帮助吗？','このブリーフィングは役立ちましたか？'),
  yes: row('도움됐어요','Helpful','有帮助','役立った'), no: row('별로였어요','Not helpful','帮助不大','あまり役立たなかった'),
  work: row('실제 영업 준비에 참고했나요?','Did you use it to prepare for work?','实际营业准备时参考了吗？','実際の営業準備に参考にしましたか？'),
  workYes: row('네','Yes','是','はい'), workNo: row('아니요','No','否','いいえ'),
  thanks: row('의견을 남겼어요. 감사합니다.','Feedback saved. Thank you.','意见已保存，谢谢。','ご意見を記録しました。ありがとうございます。'),
  analytics: row('서비스 개선을 위한 이용 통계 보내기 (선택)','Share usage statistics to improve the service (optional)','发送使用统计以改善服务（可选）','サービス改善のため利用統計を送信（任意）'),
  analyticsNote: row('동의하면 Google Analytics로 선택한 역할·지역과 버튼 이용을 보냅니다. 이름·이메일은 보내지 않으며 언제든 끌 수 있어요.','If enabled, Google Analytics receives your chosen role, place and button activity. No name or email is sent. You can turn this off anytime.','开启后会向 Google Analytics 发送所选角色、地点与按钮使用情况。不发送姓名或邮箱，可随时关闭。','同意すると選択した役割・場所・ボタン操作を Google Analytics に送信します。氏名・メールは送信せず、いつでも停止できます。'),
  install: row('앱처럼 설치하면 다음 방문에도 내 설정을 바로 볼 수 있어요.','Install as an app to return straight to your settings.','安装为应用，下次直接查看个人设置。','アプリとしてインストールすると次回も自分の設定ですぐ確認できます。'),
  push: row('매일 브리핑 알림 · 준비 중','Daily briefing notifications · in preparation','每日简报通知 · 准备中','毎日のブリーフィング通知・準備中'),
  pushNote: row('아직 알림을 보내지 않아요. 지금은 앱을 열어 브리핑을 확인해 주세요.','Notifications are not sent yet. Open the app to see your briefing.','目前不会发送通知。请打开应用查看简报。','まだ通知は送信しません。アプリを開いてご確認ください。'),
  selectedOnly: row('선택한 지역에서 제공되는 정보만 표시해요.','Only information available for your place is shown.','仅显示所选地区提供的信息。','選択した場所で提供される情報のみ表示します。'),
};
export type PersonalCopyKey = keyof typeof personalCopy;
export function pc(key: PersonalCopyKey, lang: PersonalLang) { return personalCopy[key][lang]; }
